### ISSUE TITLE
ClippingBezier for macOS ?

### ISSUE THREAD

**Issue by maculateConception** [adamwulf/ClippingBezier#23]
Hi, I apologize if this question is inappropriate or unwelcome here, but I am asking this out of pure desperation. Out of every trillion Google results, 1 result is for macOS with the rest being for iOS. So, as a macOS developer, I am just totally unable to find anything for macOS (NSBezierPath).

Is there anything like your library for macOS (NSBezierPath) ? Alternatively, can you suggest some pointers for me to be able to translate your code to work for macOS (NSBezierPath) ? I took a look at your code, and it looks like it would be very intimidating to convert it for macOS and in Swift.

Great work, and I much appreciate your response !

**Comment by adamwulf** [comment]
You might also have luck with Andy Finnell's VectorBoolean. there's a few different versions floating around - I have a clone of the original bitbucket version at https://github.com/adamwulf/vectorboolean.

If that doesn't work for you - there's also a good chance spending a day replacing `UIBezierPath` with `NSBezierPath` and rebuilding ClippingBezier would do the trick. The same would need to be done for PerformanceBezier, but I can't think of anything off the top of my head that would prevent the code from being fairly 'easily' ported to mac.

**Comment by maculateConception** [comment]
I really appreciate the quick response ! Thank you.

I will take a look at VectorBoolean and alternatively, porting your code to macOS.
