### ISSUE TITLE
ClippingBezier does not build in Xcode 15.0.0 anymore "import of C++ module appears within extern "C" language linkage specification

### ISSUE THREAD

**Issue by Litome** [adamwulf/ClippingBezier#31]
Looks like Apple has changed something in the C / C++ compiler settings when they release xCode 15.0.0 and now, when trying to build our app that uses ClippingBezier as a pod, I see this:
![Screenshot 2023-09-25 at 14 13 49](https://github.com/adamwulf/ClippingBezier/assets/7604725/7880eef2-0e71-439a-958f-285c9eeface5)

Note that it builds fine in Xcode 14.3.1

This seems to be a similar issue as reported here: https://stackoverflow.com/questions/77113501/xcode-15-compile-error-import-of-c-module-zlib-appears-within-extern-c-la

So, applying the suggested fix and modifying file `NearestPoint.h`
from:
```
#ifndef __ClippingBezier__NearestPoint__
#define __ClippingBezier__NearestPoint__

#if defined __cplusplus
extern "C" {
#endif

#import <CoreGraphics/CoreGraphics.h>
#include <stdio.h>
``` 

to:
```
#ifndef __ClippingBezier__NearestPoint__
#define __ClippingBezier__NearestPoint__

#import <CoreGraphics/CoreGraphics.h>

#if defined __cplusplus
extern "C" {
#endif


#include <stdio.h>
```
fixes it for me and enables me to compile my app using ClippingBezier with Xcode 15. 

I am not sure if this solution is the correct fix but if you're happy with it, I'm happy to create a PR for it.

**Comment by adamwulf** [comment]
Thanks for tracking that down! that solution looks correct to me, and a PR would be fantastic, thanks 🙏

**Comment by Litome** [comment]
OK. Pull request is ready here: 
https://github.com/adamwulf/ClippingBezier/pull/32

**Comment by Litome** [comment]
@adamwulf What's your timescale for creating a new tagged version?

**Comment by adamwulf** [comment]
I'll likely be able to get to it this weekend

**Comment by adamwulf** [comment]
@Litome just pushed up tag 1.2.3
