### ISSUE TITLE
boundsForElement function is missing kCGPathElementAddQuadCurveToPoint type

### ISSUE THREAD

**Issue by cjycsm** [adamwulf/ClippingBezier#36]
Here are two paths:
```
UIBezierPath *path1 = [UIBezierPath bezierPath];
[path1 moveToPoint:CGPointMake(0, 0)];
[path1 addLineToPoint:CGPointMake(200, 95)];
```
```
UIBezierPath *path2 = [UIBezierPath bezierPath];
[path2 moveToPoint:CGPointMake(100, 100)];
[path2 addQuadCurveToPoint:CGPointMake(200, 90) controlPoint:CGPointMake(150, 250)];
```
Current codes can't find intersections of these two paths.
<img width="515" alt="截屏2024-01-02 17 44 59" src="https://github.com/adamwulf/ClippingBezier/assets/39119122/c7c7074d-42fb-4f9d-b115-bffcc164ce4d">

I found that the reason was that the `kCGPathElementAddQuadCurveToPoint` type wasn't enumerated in `boundsForElement` function.

<img width="906" alt="截屏2024-01-02 17 41 37" src="https://github.com/adamwulf/ClippingBezier/assets/39119122/e1a3c9c4-b823-4974-adb1-02ed28a61fe9">

**Comment by adamwulf** [comment]
Fixed in #38
